const express = require('express')
const app = express()
const request = require('request')
const WooCommerceAPI = require('woocommerce-api')
const async = require('async')

var dataObj =   [
  {
    "Estamento": "Profesional",
    "Nombre completo": "ABARCA GARRIDO, CRISTINA ISABEL",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.766.749",
    "Montos y horas extraordinarias diurnas": "$83.760",
    "horas extra diurna": 12,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ABARZUA HERNANDEZ, ALEJANDRA CECILIA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "IX Región de la Araucanía",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.822.537",
    "Montos y horas extraordinarias diurnas": "$124.969",
    "horas extra diurna": 19,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-09-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ABARZUA RODRIGUEZ, MARCELA PAZ",
    "Cargo o función": "TÉCNICO DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "INGENIERO DE EJECUCIÓN EN ADMINISTRACION /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.047.005",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-02-2014",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ABDO CALVO, YASMIN AMAL",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO",
    "Región": "XV Región de Arica y Parinacota",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.200.803",
    "Montos y horas extraordinarias diurnas": "$78.660",
    "horas extra diurna": 12,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-09-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ABELIUK ROJAS, GLORIA MARIA OLGA",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.085.310",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2006",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ABELLO OVANDO, MARIELA DEL PILAR",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO DE NIVEL MEDIO AGRÍCOLA",
    "Región": "XI Región de Aysén",
    "Asignaciones especiales": -37,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.139.205",
    "Montos y horas extraordinarias diurnas": "$27.353",
    "horas extra diurna": 9,
    "Montos y horas extraordinarias nocturnas": "$124,001 : 34.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "08-05-2017",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ABELLO QUEZADA, CARMEN GLORIA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 15,
    "Calificación profesional o formación": "INGENIERO EN EJECUCIÓN AGRÍCOLA /",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.528.341",
    "Montos y horas extraordinarias diurnas": "$111.680",
    "horas extra diurna": 16,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2002",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ABRIGO GONZALEZ, MARIA JOSE",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO COMERCIAL / CONTADOR AUDITOR /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.760.018",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "11-04-2011",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ABURTO CERNA, ABRAHAM",
    "Cargo o función": "TÉCNICO LABORATORIO",
    "Grado EUS / Cargo con jornada": 14,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "VIII Región del Biobío",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.076.546",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "08-05-1996",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Administrativo",
    "Nombre completo": "ABURTO GOMEZ, GLORIA",
    "Cargo o función": "SECRETARIA/O",
    "Grado EUS / Cargo con jornada": 16,
    "Calificación profesional o formación": "ENSEÑANZA MEDIA",
    "Región": "X Región de los Lagos",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 943.969,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "15-07-1996",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ABURTO PRIETO, ALEJANDRA ELENA",
    "Cargo o función": "JEFE/A DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 6,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "3.056.158",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "11-05-1998",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ACEITON HERRERA, INGRID EVELYN",
    "Cargo o función": "INSPECTOR/A",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -1,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 852.121,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2014",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Auxiliar",
    "Nombre completo": "ACEITUNO ROA, LUIS GILBERTO",
    "Cargo o función": "AUXILIAR",
    "Grado EUS / Cargo con jornada": 19,
    "Calificación profesional o formación": "ENSEÑANZA BASÍCA",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 793.686,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ACENCIO EUGENIO, CARMEN MARIANELA",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 862.014,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ACEVEDO GONZALEZ, IRMA ESTELA",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 8,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.609.289",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-04-1993",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ACEVEDO GUERRA, GILBERTO JAIME",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 16,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 905.038,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "14-06-1993",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ACEVEDO MUÑOZ, BERNARDITA DE LOURDES",
    "Cargo o función": "TÉCNICO DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 12,
    "Calificación profesional o formación": "INGENIERO DE EJECUCIÓN EN ADMINISTRACION, MENCIÓN ADMINISTRACION PUBLICA / CONTADOR /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.897.784",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-07-2009",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ACEVEDO PARDO, ORIANA DEL CARMEN",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.766.749",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ACEVEDO VIDAL, ELENA DE LAS MERCEDES",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "PRACTICO AGRÍCOLA",
    "Región": "VI Región de O'Higgins",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 807.828,
    "Montos y horas extraordinarias diurnas": "$57.092",
    "horas extra diurna": 13,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ACOSTA ALVAREZ, PAULA ANTONIA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 10,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.267.787",
    "Montos y horas extraordinarias diurnas": "$129.857",
    "horas extra diurna": 16,
    "Montos y horas extraordinarias nocturnas": "$256,060 : 31.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "13-03-1995",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ACUÑA ALVAREZ, YANET ELVIRA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 12,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.924.272",
    "Montos y horas extraordinarias diurnas": "$168.603",
    "horas extra diurna": 24,
    "Montos y horas extraordinarias nocturnas": "$405,460 : 48.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "06-02-2006",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ACUÑA CARMONA, PATRICIO ENRIQUE",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "VIII Región del Biobío",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.541.427",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-1994",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ACUÑA CRUZ, FELIPE IGNACIO",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO DE NIVEL SUPERIOR AGRÍCOLA Y GANADERO",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 857.067,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ACUÑA MONROY, MARIA ELIZABETH",
    "Cargo o función": "TÉCNICO REGIONAL",
    "Grado EUS / Cargo con jornada": 16,
    "Calificación profesional o formación": "ADMINISTRADOR DE LA GESTIÓN PUBLICA",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.364.159",
    "Montos y horas extraordinarias diurnas": "$49.678",
    "horas extra diurna": 10,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-04-1989",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ADRIASOLA CASTRO, SYLVIO REINALDO",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 6,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "3.114.104",
    "Montos y horas extraordinarias diurnas": "$24.681",
    "horas extra diurna": 2,
    "Montos y horas extraordinarias nocturnas": "$29,618 : 2.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "03-06-1975",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUAYO BARHAM, CAROLINA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "BIOQUÍMICO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -1,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.701.492",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "18-07-2016",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUAYO SAN JUAN, CARLA CECILIA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "VI Región de O'Higgins",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.773.480",
    "Montos y horas extraordinarias diurnas": "$26.533",
    "horas extra diurna": 4,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2011",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "AGUILA VARGAS, SERGIO ANDRES",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO UNIVERSITARIO AGRÍCOLA",
    "Región": "IX Región de la Araucanía",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 907.955,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUILAR MATUS, FERNANDO JAVIER",
    "Cargo o función": "PROFESIONAL",
    "Grado EUS / Cargo con jornada": 7,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.823.561",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-1994",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUILAR RIOS, FERNANDO AMERICO",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "I Región de Tarapacá",
    "Asignaciones especiales": -37,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.678.565",
    "Montos y horas extraordinarias diurnas": "$165.208",
    "horas extra diurna": 18,
    "Montos y horas extraordinarias nocturnas": "$352,444 : 32.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "15-11-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "AGUILERA AGUILERA, JUAN CARLOS",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 857.067,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-12-2014",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUILERA CAMPOS, JOSE ALBERTO",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.760.018",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-09-2014",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "AGUILERA GARRIDO, RENE CRISTIAN",
    "Cargo o función": "TÉCNICO REGIONAL",
    "Grado EUS / Cargo con jornada": 15,
    "Calificación profesional o formación": "TÉCNICO DE NIVEL SUPERIOR AGRÍCOLA, MENCIÓN CULTIVOS, FRUTALES Y VIDES",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -1,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 941.876,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUILERA GUZMAN, RICARDO RUBEN",
    "Cargo o función": "PROFESIONAL REGIONAL",
    "Grado EUS / Cargo con jornada": 8,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.579.618",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-03-1994",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUILERA PLAZA, MARCELA INES",
    "Cargo o función": "ENCARGADO/A SECCIÓN TÉCNICA",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.758.705",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "AGUILLON MUÑOZ, BRENDA YICEL",
    "Cargo o función": "TÉCNICO REGIONAL",
    "Grado EUS / Cargo con jornada": 16,
    "Calificación profesional o formación": "SECRETARIA ADMINISTRATIVA /",
    "Región": "IX Región de la Araucanía",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 949.31,
    "Montos y horas extraordinarias diurnas": "$58.381",
    "horas extra diurna": 18,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGUIRRE CRISTI, RODRIGO ANDRES",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "PSICOLOGO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.092.810",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AGURTO RAMIREZ, ANDREA ALEJANDRA",
    "Cargo o función": "ENCARGADO/A SECCIÓN SOPORTE",
    "Grado EUS / Cargo con jornada": 8,
    "Calificación profesional o formación": "INGENIERO CIVIL INDUSTRIAL /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.559.838",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AHUMADA CAMPOS, MARIO ANDRES",
    "Cargo o función": "JEFE/A DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 7,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.823.561",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-1995",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "AHUMADA GAJARDO, CAROLYN VARINIA",
    "Cargo o función": "TÉCNICO LABORATORIO",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO SUPERIOR DE LABORATORIO CLÍNICO Y BANCO DE SANGRE",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -1,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 807.588,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-02-2017",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AHUMADA HENRIQUEZ, LILIAN ROXANA",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 10,
    "Calificación profesional o formación": "ADMINISTRADOR PÚBLICO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.227.342",
    "Montos y horas extraordinarias diurnas": "$42.508",
    "horas extra diurna": 5,
    "Montos y horas extraordinarias nocturnas": "$30,606 : 3.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "AHUMADA MONTENEGRO, JORGE LUIS",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 15,
    "Calificación profesional o formación": "INGENIERO DE EJECUCIÓN AGRÍCOLA /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.521.179",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-06-2001",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "AHUMADA MONTENEGRO, SARA TERESA",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 862.014,
    "Montos y horas extraordinarias diurnas": "$29.880",
    "horas extra diurna": 6,
    "Montos y horas extraordinarias nocturnas": "$66,110 : 11.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-11-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "AHUMADA PULGAR, ALFONSO ENRIQUE",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 887.014,
    "Montos y horas extraordinarias diurnas": "$78.140",
    "horas extra diurna": 25,
    "Montos y horas extraordinarias nocturnas": "$262,551 : 70.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2010",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALANIZ MEZA, TAMARA ANDREA",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "ADMINISTRADOR PÚBLICO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.077.459",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-12-2012",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALARCON FERNANDEZ, RODRIGO ALEJANDRO",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "IX Región de la Araucanía",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.829.268",
    "Montos y horas extraordinarias diurnas": "$47.160",
    "horas extra diurna": 7,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-11-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALARCON FLORES, LORENA TERESA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "VI Región de O'Higgins",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.786.943",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2007",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALARCON HERNANDEZ, ALEX JOB",
    "Cargo o función": "TÉCNICO REGIONAL",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "CONTADOR GENERAL",
    "Región": "XV Región de Arica y Parinacota",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.452.680",
    "Montos y horas extraordinarias diurnas": "$136.406",
    "horas extra diurna": 32,
    "Montos y horas extraordinarias nocturnas": "$179,034 : 35.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-2001",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Administrativo",
    "Nombre completo": "ALARCON MORA, NANCY DE LOURDES",
    "Cargo o función": "SECRETARIA/O",
    "Grado EUS / Cargo con jornada": 18,
    "Calificación profesional o formación": "LICENCIA EDUCACION MEDIA/TÉCNICO ADM EMPRESAS",
    "Región": "X Región de los Lagos",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 870.833,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-07-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALARCON MUÑOZ, JUAN AUGUSTO",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.384.352",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2007",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALARCON NIGOEVIC, EDELYN AIDA",
    "Cargo o función": "SECRETARIA/O",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "SECRETARIA EJECUTIVA / RELACIONADOR PÚBLICO",
    "Región": "IX Región de la Araucanía",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.844.456",
    "Montos y horas extraordinarias diurnas": "$161.408",
    "horas extra diurna": 24,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-1991",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALARCON PAREDES, YOHANA CAROLINA",
    "Cargo o función": "PROFESIONAL REGIONAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO",
    "Región": "XII Región de Magallanes",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.216.604",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "15-10-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALARCON SAEZ, FERNANDO ANDRES",
    "Cargo o función": "TÉCNICO DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO PROGRAMACIÓN COMPUTADORES",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 871.907,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALARCÓN SEPÚLVEDA, MARGARITA DEL CARMEN",
    "Cargo o función": "TÉCNICO LABORATORIO",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "VIII Región del Biobío",
    "Asignaciones especiales": -37,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 853.529,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-07-2017",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALBARRAN TOLEDO, ALEXIS ALEJANDRO",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "INGENIERO AGRÍCOLA, MENCIÓN CULTIVOS AGRÍCOLAS Y VIDES / TÉCNICO AGROPECUARIO DE NIVEL MEDIO",
    "Región": "IX Región de la Araucanía",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.302.326",
    "Montos y horas extraordinarias diurnas": "$18.115",
    "horas extra diurna": 4,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALBERT SERRANO, ANDRES JAVIER",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.085.310",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "15-11-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALCAIDE VALDIVIESO, MARCELA FELISA",
    "Cargo o función": "TÉCNICO DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "INGENIERO EJECUCIÓN AMBIENTAL /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.047.005",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "05-06-1998",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Auxiliar",
    "Nombre completo": "ALCAYAGA QUISPE, LUIS BERNARDO",
    "Cargo o función": "AUXILIAR",
    "Grado EUS / Cargo con jornada": 19,
    "Calificación profesional o formación": "ENS. MEDIA COMPLETA LABORAL",
    "Región": "XV Región de Arica y Parinacota",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.007.058",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALCAZAR GUERRERO, LUIS ALEJANDRO",
    "Cargo o función": "ENCARGADO/A SECCIÓN SOPORTE",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "TÉCNICO EN TURISMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.342.039",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "20-12-1995",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALCOTA AVILA, FRANCISCO JAVIER",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "III Región de Atacama",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 933.636,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2014",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALDANA PEREZ, JOSE FERNANDO",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO PRODUCCION AGROPECUARIA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 866.96,
    "Montos y horas extraordinarias diurnas": "$89.640",
    "horas extra diurna": 18,
    "Montos y horas extraordinarias nocturnas": "$199,733 : 40.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2010",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALDERETE ORELLANA, CRISTIAN RODRIGO",
    "Cargo o función": "TÉCNICO REGIONAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "II Región de Antofagasta",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.081.035",
    "Montos y horas extraordinarias diurnas": "$16.060",
    "horas extra diurna": 5,
    "Montos y horas extraordinarias nocturnas": "$131,048 : 34.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "15-09-1997",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALEGRIA CERDA, ALEXANDER ANTHONY",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "XV Región de Arica y Parinacota",
    "Asignaciones especiales": -37,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.056.100",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "$262,591 : 72.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2016",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALEGRIA VIDAL, RODRIGO IVAN",
    "Cargo o función": "TÉCNICO DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 15,
    "Calificación profesional o formación": "TÉCNICO ANALISTA COMPUTACION",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 953.418,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2002",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALEMANY ESPARZA, SOLEDAD PILAR",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 15,
    "Calificación profesional o formación": "INGENIERO DE EJECUCIÓN FORESTAL /",
    "Región": "VIII Región del Biobío",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.569.558",
    "Montos y horas extraordinarias diurnas": "$27.920",
    "horas extra diurna": 4,
    "Montos y horas extraordinarias nocturnas": "$66,080 : 8.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Administrativo",
    "Nombre completo": "ALFARO PARRA, RODRIGO ANDRES",
    "Cargo o función": "ADMINISTRATIVO",
    "Grado EUS / Cargo con jornada": 18,
    "Calificación profesional o formación": "ENSEÑANZA MEDIA /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 828.293,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-10-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Administrativo",
    "Nombre completo": "ALFARO VEGA, HORTENSIA ISABEL",
    "Cargo o función": "ADMINISTRATIVO",
    "Grado EUS / Cargo con jornada": 15,
    "Calificación profesional o formación": "SECRETARIA EJECUTIVA /",
    "Región": "III Región de Atacama",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.042.743",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2002",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALIAGA CORNEJO, CLAUDIO",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 10,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "VI Región de O'Higgins",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.288.009",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "23-05-1988",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Administrativo",
    "Nombre completo": "ALIAGA ROJAS, LUIS EDUARDO",
    "Cargo o función": "ADMINISTRATIVO",
    "Grado EUS / Cargo con jornada": 18,
    "Calificación profesional o formación": "ENSEÑANZA MEDIA COMPLETA",
    "Región": "IV Región de Coquimbo",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 856.653,
    "Montos y horas extraordinarias diurnas": "$26.532",
    "horas extra diurna": 9,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Administrativo",
    "Nombre completo": "ALLENDE MENESES, MARIA ANTONIETA",
    "Cargo o función": "ADMINISTRATIVO",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "SECRETARIA ADMINISTRATIVA / NGENIERO EJECUCIÓN ADMINISTRACION",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.266.278",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-09-1994",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALLENDE TORTORA, RODRIGO ANTONIO",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 872.041,
    "Montos y horas extraordinarias diurnas": "$96.176",
    "horas extra diurna": 22,
    "Montos y horas extraordinarias nocturnas": "$170,549 : 40.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-11-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALLENDES DIAZ, CLAUDIA ALEJANDRA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.760.018",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALLENDES MUÑOZ, CARLA ANDREA",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO PROGRAMADOR EN COMPUTACION",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -1,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 852.121,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALMARZA SERRANO, JOAQUIN DENNIS",
    "Cargo o función": "JEFE/A SUBDEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.384.352",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2007",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALMONACID PACHECO, MARCELA IVETTE",
    "Cargo o función": "PROFESIONAL REGIONAL",
    "Grado EUS / Cargo con jornada": 10,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "XIV Región de Los Ríos",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.314.574",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-11-2009",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALMUNA DIAZ, NANCY JACQUELINE",
    "Cargo o función": "PROFESIONAL REGIONAL",
    "Grado EUS / Cargo con jornada": 14,
    "Calificación profesional o formación": "PLANIFICADOR SOCIAL /",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.629.515",
    "Montos y horas extraordinarias diurnas": "$163.161",
    "horas extra diurna": 27,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-07-2001",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALTIMIRAS GONZALEZ, JAIME JESUS",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "VI Región de O'Higgins",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.766.749",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALUANLLI MARTABIT, ANTONIO ENRIQUE",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 5,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "3.276.684",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "25-07-1979",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVARADO ADROVER, GONZALO ANDRES",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 857.067,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "$18,236 : 5.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "15-10-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVARADO ESPINOSA, CAROLINA VIVIANA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.760.018",
    "Montos y horas extraordinarias diurnas": "$6.555",
    "horas extra diurna": 1,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-11-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVARADO GARCIA, PATRICIO ALEJANDRO",
    "Cargo o función": "PROFESIONAL REGIONAL",
    "Grado EUS / Cargo con jornada": 14,
    "Calificación profesional o formación": "ING. EN INFORMÁTICA",
    "Región": "IV Región de Coquimbo",
    "Asignaciones especiales": -37,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.655.638",
    "Montos y horas extraordinarias diurnas": "$23.882",
    "horas extra diurna": 4,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "16-11-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVARADO PALMA, NELSON PATRICIO",
    "Cargo o función": "JEFE/A SUBDEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 8,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.559.838",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-11-2013",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVARADO VILLARROEL, LUIS ALEXANDER",
    "Cargo o función": "INSPECTOR/A",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "XII Región de Magallanes",
    "Asignaciones especiales": -37,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.190.110",
    "Montos y horas extraordinarias diurnas": "$42.550",
    "horas extra diurna": 14,
    "Montos y horas extraordinarias nocturnas": "$156,825 : 43.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2017",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ ALFARO, ANDRES RODRIGO",
    "Cargo o función": "JEFE/A SUBDEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 8,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.559.838",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVAREZ BERRIOS, JUAN HORACIO",
    "Cargo o función": "TÉCNICO DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "CONTADOR /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.078.764",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-1981",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVAREZ CAMPOS, EDUARDO GABRIEL",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 857.067,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ CARCAMO, JUAN FRANCISCO",
    "Cargo o función": "PROFESIONAL REGIONAL",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "MÉDICO VETERINARIO",
    "Región": "XII Región de Magallanes",
    "Asignaciones especiales": -37,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.854.992",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-11-1998",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVAREZ DAZA, LORENA MILEN",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 857.067,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ GONZALEZ, MAURICIO ALBERTO",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.760.018",
    "Montos y horas extraordinarias diurnas": "$39.330",
    "horas extra diurna": 6,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVAREZ GUTIERREZ, LILIAN IBETH",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "T. NIVEL SUP. ESP. A",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.150.861",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "16-08-2000",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ HUITRAYAO, MARIA ALEJANDRA",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "MÉDICO VETERINARIO /",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.391.631",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "17-11-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVAREZ INSAMI, RAUL FABIAN",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 17,
    "Calificación profesional o formación": "TÉCNICO AGRÍCOLA / INGENIERO EN ACUICULTURA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.256.385",
    "Montos y horas extraordinarias diurnas": "$24.900",
    "horas extra diurna": 5,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ JARA, AILEEN NATALY",
    "Cargo o función": "PROFESIONAL REGIONAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "ADMINISTRADOR PÚBLICO /",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.773.480",
    "Montos y horas extraordinarias diurnas": "$119.399",
    "horas extra diurna": 18,
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-02-2011",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ LOPEZ, MARIA LORENA",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "MÉDICO VETERINARIO",
    "Región": "II Región de Antofagasta",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.040.172",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2006",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ MUÑOZ, JAIME FELIPE",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO SOPORTE",
    "Grado EUS / Cargo con jornada": 11,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.099.051",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-02-2008",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Administrativo",
    "Nombre completo": "ALVAREZ SILVA, RENE ALEXIS",
    "Cargo o función": "ADMINISTRATIVO",
    "Grado EUS / Cargo con jornada": 18,
    "Calificación profesional o formación": "ENSEÑANZA MEDIA / INGENIERO EJECUCIÓN EN INFORMATICA",
    "Región": "V Región de Valparaíso",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.187.004",
    "Montos y horas extraordinarias diurnas": "$28.840",
    "horas extra diurna": 7,
    "Montos y horas extraordinarias nocturnas": "$58,800 : 12.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVAREZ VILLAGRAN, MONICA BEATRIZ",
    "Cargo o función": "PROFESIONAL SECTORIAL",
    "Grado EUS / Cargo con jornada": 13,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.766.749",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2007",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Técnico",
    "Nombre completo": "ALVAREZ VITERI, PAULA ANDREA",
    "Cargo o función": "TÉCNICO SECTORIAL",
    "Grado EUS / Cargo con jornada": 15,
    "Calificación profesional o formación": "TÉCNICO PECUARIO",
    "Región": "VII Región del Maule",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": 948.26,
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-08-2007",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Profesional",
    "Nombre completo": "ALVEAR HERNANDEZ, FRANCISCA ALEJANDRA",
    "Cargo o función": "PROFESIONAL DEPARTAMENTO TÉCNICO",
    "Grado EUS / Cargo con jornada": 9,
    "Calificación profesional o formación": "INGENIERO AGRÓNOMO /",
    "Región": "Región Metropolitana",
    "Asignaciones especiales": -33,
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "2.400.788",
    "Montos y horas extraordinarias diurnas": "No tiene",
    "horas extra diurna": "",
    "Montos y horas extraordinarias nocturnas": "No tiene",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "08-10-2007",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  },
  {
    "Estamento": "Auxiliar",
    "Nombre completo": "AMAS AMAS, MOISES EDUARDO",
    "Cargo o función": "AUXILIAR",
    "Grado EUS / Cargo con jornada": 19,
    "Calificación profesional o formación": "ENSEÑANZA MEDIA",
    "Región": "XV Región de Arica y Parinacota",
    "Asignaciones especiales": "37  33",
    "Unidad monetaria": "Pesos",
    "Remuneración bruta mensualizada": "1.007.058",
    "Montos y horas extraordinarias diurnas": "$16.737",
    "horas extra diurna": 6,
    "Montos y horas extraordinarias nocturnas": "$73,643 : 22.00hrs",
    "Montos y horas extraordinarias festivas": "No tiene",
    "Fecha de inicio dd/mm/aa": "01-01-2015",
    "Fecha de término dd/mm/aa": "31-12-2017",
    "Declaración de intereses y patrimonio": "No",
    "Viáticos": "No informa",
    "Observaciones": "Sin observaciones"
  }
];


function updateEveryMethod() {
  console.log("test");
  shippingArrayID = [];
async.eachSeries(dataObj, function(data, callback) {

  request.post({
  headers: {'content-type' : 'application/json',
  'kbn-version' : '6.1.0'},
  url:     'http://35.168.202.205:5601/api/console/proxy?path=sag%2Fsag%2F&method=POST',
  body: JSON.stringify(data)
}, function(error, response, body){
    callback(null);
  console.log(body);
});

});


}

updateEveryMethod();
